# Generated by Django 5.1.5 on 2025-03-10 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('res', '0001_initial'),
        ('static', '0005_alter_client_parent_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('manifest_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('res_identifier', models.CharField(max_length=6)),
                ('res_status_identifier', models.CharField(max_length=10)),
                ('channel_identifier', models.CharField(max_length=10)),
                ('booking_platform', models.CharField(max_length=25)),
                ('check_in_date', models.CharField(max_length=10)),
                ('check_out_date', models.CharField(max_length=10)),
                ('room_number', models.CharField(max_length=6)),
                ('room_type', models.CharField(max_length=6)),
                ('guest_identifier', models.CharField(max_length=6)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=35)),
                ('gender', models.CharField(max_length=6)),
                ('birth_date', models.CharField(max_length=10)),
                ('mobile_phone_number', models.CharField(max_length=15)),
                ('natonality', models.CharField(max_length=20)),
                ('document_number', models.CharField(max_length=20)),
                ('document_type', models.CharField(max_length=6)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'manifest (bridge_manifest)',
                'db_table': 'bridge_manifest',
                'ordering': [],
            },
        ),
    ]
