# Generated by Django 5.1.5 on 2025-03-10 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='natonality',
            new_name='nationality',
        ),
    ]
