# Generated by Django 5.1.5 on 2025-04-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0003_alter_manifest_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manifest',
        ),
    ]
