# AUTO GENERATED
#  ALL
NOT_APPLICABLE = '000'                                           # not applicableTO_BE_ANNOUNCED = '999'                                          # to be announced#  Anova
USER_ANOVA = '001'                                               # anova users#  Client
COMPANY_USER_AGENT = '020'                                       # travel agents#  Crew
POSITION = '005'                                                 # position management#  Cruise Setup
EVENT = '004'                                                    # cruise managementEVENT_CATEGORY_PRICE = '019'                                     # grade pricingEVENT_CATEGORY_PRICE_DETAIL = '018'                              # grade pricing - detailEVENT_ROOM_INVENTORY = '022'                                     # cabin inventoryEVENT_ROOM_INVENTORY_SUMMARY = '023'                             # cabin inventory summarySELECT_EVENT_FOR_INVENTORY = '021'                               # select cruise for cruise inventorySELECT_EVENT_FOR_PRICING = '017'                                 # select cruise for grade pricing#  Hotel Setup
FLOOR = '009'                                                    # hotel build: decks/floorsROOM = '003'                                                     # hotel build: cabins/roomsROOM_CATEGORY = '002'                                            # hotel build: room categories#  Point of Sale
TRANSACTION_ITEM_STAGED = '006'                                  # staged transactions items#  Reservations
CLIENT_CURRENCY = '015'                                          # client currenciesCOMPANY_TRAVEL_AGENCY = '014'                                    # travel agenciesHOTEL_CURRENCY = '016'                                           # hotel currencies#  Security
ROLE = '007'                                                     # rolesROLE_MENU = '010'                                                # role menusROLE_PROCESS_DETAIL_FORM = '011'                                 # role processes detail - forrmsROLE_PROCESS_DETAIL_GRID = '013'                                 # role processes detail - gridsROLE_PROCESS_FORM = '008'                                        # role processes formsROLE_PROCESS_GRID = '012'                                        # role processes grids