# AUTO GENERATED
#  
NOT_APPLICABLE = '000'                                           # not applicable#  anovavms
ANOVAVMS_ROLE_ITEM = '01D'                                       # role itemsANOVAVMS_TRANSACTION_LIST = '00K'                                # transactionANOVAVMS_TRANSACTION_STATUS = '00S'                              # transaction status#  core
CORE_CONTEXT = '01C'                                             # application context#  forms
FORM_001 = '00Y'                                                 # form001FORM_002 = '010'                                                 # form002FORM_004 = '00T'                                                 # form004FORM_005 = '00Z'                                                 # form005#  grids
GRID_USER_ANOVA = '013'                                          # anova usersGRID_ROOM_CATEGORY = '016'                                       # room categoriesGRID_ROOM = '017'                                                # cabins/roomsGRID_POSITION = '01B'                                            # position managementGRID_EVENT = '019'                                               # cruise manangementGRID_TRANSACTION_STAGED = '01G'                                  # staged transactions#  integration
INTEGRATION_GUEST_LIST = '014'                                   # guest integrationINTEGRATION_POS_MENU_ITEM_LIST = '01F'                           # pos menu item list by roleINTEGRATION_TRANSACTION_CREATE = '015'                           # create transaction#  table
BASE_CATEGORY = '001'                                            # categoryBASE_CHART_FIELD = '002'                                         # chart fieldBASE_COMPANY = '003'                                             # companyBASE_EMAIL = '004'                                               # emailBASE_HOTEL_TYPE = '005'                                          # hotel_typeBASE_ITEM = '006'                                                # itemBASE_JOB_RUN = '00Q'                                             # job runBASE_PERSON = '007'                                              # personBASE_POS_MENU = '008'                                            # pos menuBASE_POS_MENU_ITEM = '009'                                       # pos menu /temBASE_POSITION = '00M'                                            # posittionBASE_EXCHANGE_RATE = '011'                                       # exchange ratesRES_GUEST_DETAIL = '00W'                                         # guest detailRES_GUEST_TOGGLE_STATUS = '00X'                                  # toggle guest statusRES_EVENT = '00B'                                                # eventTABLE_RES_GUEST = '00C'                                          # guestRES_GUEST_ROOM = '00D'                                           # guest/roomRES_HOTEL_EXTENSION = '00R'                                      # hotel extensionRES_HOTEL_ITEM = '00F'                                           # hotel/itemRES_RESERVATION = '00G'                                          # reservationRES_ROOM = '00J'                                                 # roomRES_TRANSACTION_ITEM = '00L'                                     # transaction/item#  table views
BASE_TABLE_JOB = '00P'                                           # job#  tablea
BASE_USER = '00V'                                                # user#  utilities
USER_PROFILE = '018'                                             # get user profile#  views
BASE_JOB_SCHEDULER = '012'                                       # process scheduled jobs