from django.urls import path

## AUTOGENERATED URL FILE ##

from apps.res.api.integration.guest import IntegrationGuestListAPIViewfrom apps.res.api.integration.item import IntegrationItemListAPIViewfrom apps.res.api.integration.transaction import IntegrationTransactionCreateAPIView

urlpatterns = [
    path('/api/v1/integration/guests/', IntegrationGuestListAPIView.as_view()),    path('/api/v1/integration/items/', IntegrationItemListAPIView.as_view()),    path('/api/v1/integration/transactions/', IntegrationTransactionCreateAPIView.as_view()),
]