# Generated by Django 5.1.5 on 2025-02-24 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('identifier_id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('last_identifier', models.IntegerField(default=0)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'identifiers (base_identifier)',
                'db_table': 'base_identifier',
                'ordering': [],
            },
        ),
    ]
