# Generated by Django 5.1.5 on 2025-03-07 22:54

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_identifier_last_updated'),
        ('static', '0003_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('grouping', models.CharField(blank=True, default='', max_length=30)),
                ('order_by', models.CharField(blank=True, default='00', max_length=2)),
                ('code', models.CharField(blank=True, max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('middle_name', models.CharField(blank=True, default='', max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('birth_date', models.DateTimeField(default=core.utilities.date_utilities.beginning_of_time)),
                ('person_key', models.CharField(blank=True, default='', max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('gender_type', models.ForeignKey(default='700', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'people (base_person)',
                'db_table': 'base_person',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('access_user_id', models.CharField(default='', max_length=4)),
                ('grouping', models.CharField(blank=True, default='', max_length=30)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=40)),
                ('user_key', models.CharField(blank=True, default='', max_length=50)),
                ('start_date', models.DateTimeField(default=core.utilities.date_utilities.today)),
                ('end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('external_id', models.CharField(max_length=15)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('effective_status', models.ForeignKey(db_column='effective_status_id', default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('person', models.ForeignKey(default='A9999', on_delete=django.db.models.deletion.CASCADE, to='base.person')),
                ('type', models.ForeignKey(default='041', on_delete=django.db.models.deletion.CASCADE, to='static.type')),
            ],
            options={
                'verbose_name_plural': 'users (base_user)',
                'db_table': 'base_user',
                'ordering': [],
            },
        ),
    ]
