# Generated by Django 5.1.5 on 2025-03-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_person_person_id_alter_user_access_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='external_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='order_by',
            field=models.CharField(blank=True, default='99', max_length=2),
        ),
    ]
