# Generated by Django 5.1.5 on 2025-03-11 01:47

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_person_external_id_alter_person_order_by'),
        ('static', '0005_alter_client_parent_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('order_by', models.CharField(default='99', max_length=2)),
                ('description', models.CharField(max_length=90)),
                ('start_date', models.DateTimeField(default=core.utilities.date_utilities.beginning_of_time)),
                ('end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('grouping', models.CharField(default='', max_length=20)),
                ('category_key', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=50)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.client')),
                ('effective_status', models.ForeignKey(db_column='effective_status_id', default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('parent_category', models.ForeignKey(db_column='parent_category_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.category')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'general categories (base_category)',
                'db_table': 'base_category',
                'ordering': [],
            },
        ),
    ]
