# Generated by Django 5.1.5 on 2025-03-11 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(db_column='parent_category_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.category'),
        ),
    ]
