# Generated by Django 5.1.5 on 2025-03-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default='', max_length=15),
        ),
    ]
