# Generated by Django 5.1.5 on 2025-03-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_category_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
