# Generated by Django 5.1.5 on 2025-03-19 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_delete_category'),
        ('static', '0005_alter_client_parent_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('mapping_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('application_name', models.CharField(default='', max_length=30)),
                ('model_name', models.CharField(default='', max_length=30)),
                ('external_identifier', models.CharField(default='', max_length=50)),
                ('internal_identifier', models.CharField(default='', max_length=10)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'mappings (base_mapping)',
                'db_table': 'base_mapping',
                'ordering': [],
            },
        ),
    ]
