# Generated by Django 5.1.5 on 2025-03-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_mapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapping',
            old_name='application_name',
            new_name='app_name',
        ),
        migrations.RenameField(
            model_name='mapping',
            old_name='internal_identifier',
            new_name='internal_id',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='external_identifier',
        ),
        migrations.AddField(
            model_name='mapping',
            name='external_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
