# Generated by Django 5.1.5 on 2025-03-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_application_name_mapping_app_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mapping',
        ),
    ]
