# Generated by Django 5.1.5 on 2025-03-19 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_externalmapping_delete_mapping'),
        ('static', '0005_alter_client_parent_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='external_id',
        ),
        migrations.AddField(
            model_name='person',
            name='client',
            field=models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.client'),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status'),
        ),
    ]
