# Generated by Django 5.1.5 on 2025-03-21 13:44

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_person_external_id_person_client_and_more'),
        ('static', '0005_alter_client_parent_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(default='', max_length=15)),
                ('description', models.CharField(default='', max_length=70)),
                ('description_short', models.CharField(default='', max_length=30)),
                ('start_date', models.DateTimeField(default=core.utilities.date_utilities.beginning_of_time)),
                ('end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('grouping', models.CharField(default='', max_length=40)),
                ('company_key', models.CharField(default='', max_length=70)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.client')),
                ('effective_status', models.ForeignKey(default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='static.type')),
            ],
            options={
                'verbose_name_plural': 'companies (base_company)',
                'db_table': 'base_company',
                'ordering': [],
            },
        ),
    ]
