# Generated by Django 5.1.5 on 2025-03-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.TextField(blank=True, default=''),
        ),
    ]
