# Generated by Django 5.1.5 on 2025-04-11 15:46

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_person_email'),
        ('static', '0008_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartField',
            fields=[
                ('chart_field_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=15)),
                ('description', models.CharField(max_length=254)),
                ('description_short', models.CharField(default='', max_length=40)),
                ('start_date', models.DateTimeField(default=core.utilities.date_utilities.beginning_of_time)),
                ('end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('effective_status', models.ForeignKey(default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('hotel', models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='static.type')),
            ],
            options={
                'verbose_name_plural': 'Chart Fields (base_chart_field)',
                'db_table': 'base_chart_field',
                'ordering': [],
            },
        ),
    ]
