# Generated by Django 5.1.5 on 2025-04-14 21:24

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_category'),
        ('static', '0008_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(default='', max_length=15)),
                ('description', models.CharField(default='', max_length=90)),
                ('order_by', models.CharField(default='99', max_length=2)),
                ('start_date', models.DateTimeField(default=core.utilities.date_utilities.beginning_of_time)),
                ('end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('grouping', models.CharField(default='', max_length=40)),
                ('item_key', models.CharField(default='', max_length=40)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default='A0000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.category')),
                ('effective_status', models.ForeignKey(db_column='effective_status_id', default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'items (base_item)',
                'db_table': 'base_item',
                'ordering': [],
            },
        ),
    ]
