# Generated by Django 5.1.5 on 2025-04-18 20:48

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_item'),
        ('static', '0008_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosMenu',
            fields=[
                ('pos_menu_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('menu_start_date', models.DateTimeField(default=core.utilities.date_utilities.today)),
                ('menu_end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('start_date', models.DateTimeField(default=core.utilities.date_utilities.beginning_of_time)),
                ('end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default='A9999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.category')),
                ('currency', models.ForeignKey(default='00', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.currency')),
                ('effective_status', models.ForeignKey(default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('hotel', models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'Pont of Sale Menus (base_pos_menu)',
                'db_table': 'base_pos_menu',
                'ordering': [],
            },
        ),
    ]
