# Generated by Django 5.1.5 on 2025-04-22 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_posmenuitem'),
        ('static', '0010_delete_posmenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalmapping',
            name='external_pk',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='HotelType',
            fields=[
                ('hotel_type_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel')),
                ('item', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.item')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'hotel types (base_hotel_type)',
                'db_table': 'base_hotel_type',
                'ordering': [],
            },
        ),
    ]
