# Generated by Django 5.1.5 on 2025-04-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_arcfunction_hotelitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArcFunction',
        ),
    ]
