# Generated by Django 5.1.5 on 2025-04-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_delete_arcfunction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelItem',
        ),
    ]
