# Generated by Django 5.1.5 on 2025-07-02 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_delete_hotelitem'),
        ('static', '0014_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.ForeignKey(default='041', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type'),
        ),
    ]
