# Generated by Django 5.1.5 on 2025-07-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_eventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='client_ip',
            field=models.CharField(default='', max_length=15),
        ),
    ]
