# Generated by Django 5.1.12 on 2025-10-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_eventlog_client_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'user hotels junction (base_user_hotel)',
                'db_table': 'base_user_hotel',
                'ordering': [],
            },
        ),
    ]
