# Generated by Django 5.1.12 on 2025-10-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_userhotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHotel',
        ),
    ]
