# Generated by Django 5.1.12 on 2025-10-19 13:08

import core.utilities.date_utilities
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_delete_userhotel'),
        ('static', '0018_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHotel',
            fields=[
                ('user_hotel_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateTimeField(default=core.utilities.date_utilities.beginning_of_time)),
                ('end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('effective_status', models.ForeignKey(db_column='effective_status_id', default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('hotel', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
                ('user', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user hotels junction (base_user_hotel)',
                'db_table': 'base_user_hotel',
                'ordering': [],
            },
        ),
    ]
