# Generated by Django 5.1.12 on 2025-10-19 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_userhotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhotel',
            name='user',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='userHotels', to=settings.AUTH_USER_MODEL),
        ),
    ]
