# Generated by Django 5.1.12 on 2025-10-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_userhotel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='salutation',
            field=models.CharField(blank=True, default='', help_text='mr., mrs....', max_length=8),
        ),
    ]
