# Generated by Django 5.1.12 on 2025-11-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_person_salutation'),
        ('static', '0022_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('grouping', models.CharField(blank=True, default='', max_length=40)),
                ('code', models.CharField(blank=True, default='', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=40)),
                ('role_key', models.CharField(default='', max_length=40)),
                ('group1', models.CharField(blank=True, default='', max_length=15)),
                ('group2', models.CharField(blank=True, default='', max_length=15)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel')),
                ('parent_role', models.ForeignKey(db_column='parent_role_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.role')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'roles (base_role)',
                'db_table': 'base_role',
                'ordering': [],
            },
        ),
    ]
