# Generated by Django 5.1.12 on 2025-11-30 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_roleprocess'),
        ('static', '0023_remove_process_id_alter_process_process_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=60)),
                ('email', models.TextField(default='')),
                ('grouping', models.CharField(default='', max_length=30)),
                ('position_key', models.CharField(default='', max_length=50)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel')),
                ('parent_position', models.ForeignKey(db_column='parent_position_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.position')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'Positions (base_position)',
                'db_table': 'base_position',
                'ordering': [],
            },
        ),
    ]
