# Generated by Django 5.1.12 on 2025-12-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_position'),
        ('static', '0023_remove_process_id_alter_process_process_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('order_by', models.CharField(default='99', max_length=2)),
                ('code', models.CharField(default='', max_length=50)),
                ('frequency', models.CharField(default='#', help_text='#=On Demand D=daily H=hourly', max_length=1)),
                ('description', models.CharField(default='', max_length=60)),
                ('grouping', models.CharField(blank=True, default='', max_length=30)),
                ('job_key', models.CharField(default='', max_length=60)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'job definitions (base_job)',
                'db_table': 'base_job',
                'ordering': [],
            },
        ),
    ]
