# Generated by Django 5.1.12 on 2026-02-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_jobrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='string05',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='string06',
            field=models.CharField(default='', max_length=255),
        ),
    ]
