# Generated by Django 5.1.12 on 2026-02-11 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_eventlog_string05_eventlog_string06'),
        ('static', '0028_formextra_target_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('parameter_id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('client_ip', models.CharField(default='', max_length=15)),
                ('string01', models.CharField(default='', max_length=255)),
                ('string02', models.CharField(default='', max_length=255)),
                ('string03', models.CharField(default='', max_length=255)),
                ('string04', models.CharField(default='', max_length=255)),
                ('string05', models.CharField(default='', max_length=255)),
                ('string06', models.CharField(default='', max_length=255)),
                ('text01', models.TextField(default='')),
                ('text02', models.TextField(default='')),
                ('text03', models.TextField(default='')),
                ('list01', models.TextField(default='')),
                ('list02', models.TextField(default='')),
                ('list03', models.TextField(default='')),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('access_user', models.ForeignKey(default='A99999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
                ('user', models.ForeignKey(default='A99999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'parameters (base_parameter)',
                'db_table': 'base_parameter',
                'ordering': [],
            },
        ),
        migrations.DeleteModel(
            name='EventLog',
        ),
    ]
