# Generated by Django 5.1.12 on 2026-02-12 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_parameter_delete_eventlog'),
        ('static', '0029_formfield_mapping_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.ForeignKey(default='00Q', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.ForeignKey(default='010', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status'),
        ),
    ]
