# Generated by Django 5.1.12 on 2026-02-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_user_status_user_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='string07',
            field=models.CharField(default='', max_length=255),
        ),
    ]
