# Generated by Django 5.1.12 on 2026-02-12 13:53

import core.utilities.date_utilities
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_parameter_string07'),
        ('static', '0029_formfield_mapping_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('user_verfication_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('email_sent_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('verification_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user verification (base_user_verification)',
                'db_table': 'base_user_verification',
                'ordering': [],
            },
        ),
    ]
