# Generated by Django 5.1.12 on 2026-02-12 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_user_status_alter_user_verification_status'),
        ('static', '0029_formfield_mapping_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(default='00Q', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.ForeignKey(default='010', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status'),
        ),
    ]
