# Generated by Django 5.1.12 on 2026-02-22 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_alter_user_status_alter_user_verification_status'),
        ('static', '0030_formfield_custom_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_hotel',
            field=models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel'),
        ),
    ]
