# Generated by Django 5.1.12 on 2026-02-23 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_user_last_hotel'),
        ('static', '0030_formfield_custom_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleprocess',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.process'),
        ),
    ]
