# Generated by Django 5.1.12 on 2026-03-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_alter_roleprocess_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='position',
            name='email',
            field=models.CharField(default='', max_length=254),
        ),
    ]
