# Generated by Django 5.1.12 on 2026-03-12 18:47

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_emailqueue'),
        ('static', '0033_alter_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailqueue',
            name='person',
            field=models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, to='base.person'),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='sent_date',
            field=models.DateTimeField(default=core.utilities.date_utilities.end_of_time),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='status',
            field=models.ForeignKey(default='019', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status'),
        ),
    ]
