# Generated by Django 5.1.12 on 2026-03-13 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_emailqueue_person_alter_emailqueue_sent_date_and_more'),
        ('static', '0035_remove_formfield_max_characters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('service_request_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('industry_other', models.CharField(default='', max_length=60)),
                ('subject', models.CharField(default='000', max_length=80)),
                ('body', models.TextField(default='')),
                ('company_name', models.CharField(default='', max_length=20)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('industry_type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
                ('person', models.ForeignKey(default='A99999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.person')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'service requests (base_service_request)',
                'db_table': 'base_service_request',
                'ordering': [],
            },
        ),
    ]
