# Generated by Django 5.1.12 on 2026-03-14 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_servicerequest'),
        ('static', '0035_remove_formfield_max_characters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('period_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(default='', max_length=15)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grouping', models.CharField(blank=True, default='', max_length=30)),
                ('period_key', models.CharField(max_length=20)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('effective_status', models.ForeignKey(default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'periods months, days (base_period)',
                'db_table': 'base_period',
                'ordering': [],
            },
        ),
        migrations.DeleteModel(
            name='UserVerification',
        ),
    ]
