# Generated by Django 5.1.12 on 2026-03-14 15:20

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_userverification'),
        ('res', '0040_alter_guestroom_guest'),
        ('static', '0035_remove_formfield_max_characters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('exchange_rate_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('start_date', models.DateTimeField(default=core.utilities.date_utilities.beginning_of_time)),
                ('end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(default='00', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.currency')),
                ('effective_status', models.ForeignKey(default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('event', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.event')),
                ('period', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.period')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static.type')),
            ],
            options={
                'verbose_name_plural': 'exhange rates (base_exchange_rate)',
                'db_table': 'base_exchange_rate',
                'ordering': [],
            },
        ),
    ]
