# Generated by Django 5.1.12 on 2026-03-16 13:32

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_exchangerate'),
        ('static', '0035_remove_formfield_max_characters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='frequency_type',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type'),
        ),
        migrations.CreateModel(
            name='JobExtension',
            fields=[
                ('job_extension_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('last_run_time', models.DateTimeField(default=core.utilities.date_utilities.beginning_of_time)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(default='A00', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.job')),
            ],
            options={
                'verbose_name_plural': 'job definitions extension (base_job_extension)',
                'db_table': 'base_job_extension',
                'ordering': [],
            },
        ),
    ]
