# Generated by Django 5.1.12 on 2026-03-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_job_frequency_type_jobextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
    ]
