# Generated by Django 5.1.12 on 2026-03-26 12:49

import core.utilities.date_utilities
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_exchangerate_rate'),
        ('static', '0036_currency_currency_key_currency_grouping'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('role_menu_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('effective_status', models.ForeignKey(default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('menu', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.menu')),
                ('role', models.ForeignKey(default='A999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.role')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'Role/Menu junction (base_role_menu)',
                'db_table': 'base_role_menu',
                'ordering': [],
            },
        ),
    ]
