# Generated by Django 5.1.12 on 2026-03-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_rolemenu'),
        ('static', '0036_currency_currency_key_currency_grouping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemenu',
            name='menu',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.menu'),
        ),
    ]
