# Generated by Django 5.1.12 on 2026-04-03 19:19

import core.utilities.date_utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_alter_rolemenu_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=core.utilities.date_utilities.beginning_of_time),
        ),
    ]
