# Generated by Django 5.1.12 on 2026-04-17 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_log'),
        ('static', '0049_process_generate_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='process',
            field=models.ForeignKey(default='000', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.process'),
        ),
    ]
