# Generated by Django 5.1.12 on 2026-04-23 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_log_process'),
        ('static', '0051_grid_data_source_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleItem',
            fields=[
                ('role_item_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('allow_api_charge', models.BooleanField(default=False)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.item')),
                ('role', models.ForeignKey(default='A999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.role')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'role items (base_role_item)',
                'db_table': 'base_role_item',
                'ordering': [],
            },
        ),
    ]
