# Generated by Django 5.1.12 on 2026-05-20 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_alter_userrole_role_alter_userrole_user'),
        ('static', '0056_menu_hotel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=60)),
                ('external_code', models.CharField(default='', help_text='unlocode/iata_code/icao_code/iso_code', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=60)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('parent_location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.location')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'locations (ports, states, etc) (base_location)',
                'db_table': 'base_location',
                'ordering': [],
            },
        ),
    ]
