# Generated by Django 5.1.12 on 2026-05-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='grouping',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='location',
            name='location_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
