# Generated by Django 5.1.12 on 2026-07-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_hotelcurrency'),
        ('static', '0064_alter_currency_currency_key'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hotelcurrency',
            name='unique_hotel_currency',
        ),
        migrations.AddConstraint(
            model_name='hotelcurrency',
            constraint=models.UniqueConstraint(fields=('hotel', 'currency'), name='unique_hotel_currency'),
        ),
    ]
