# Generated by Django 5.1.12 on 2026-08-07 11:53

import core.utilities.date_utilities
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_remove_hotelcurrency_unique_client_currency_and_more'),
        ('static', '0066_gridcolumn_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('company_user_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('order_by', models.CharField(blank=True, default='99', max_length=2)),
                ('office_phone', models.CharField(default='', max_length=30)),
                ('extension', models.CharField(default='', max_length=30)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(default=core.utilities.date_utilities.today)),
                ('end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(default='A0000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.company')),
                ('effective_status', models.ForeignKey(db_column='effective_status_id', default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
                ('user', models.ForeignKey(default='A99999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'company users (base_company_user)',
                'db_table': 'base_company_user',
                'ordering': [],
            },
        ),
    ]
