# Generated by Django 5.1.12 on 2026-08-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_companyuser'),
        ('static', '0066_gridcolumn_editable'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='companyuser',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='unique_company_user'),
        ),
    ]
