# Generated by Django 5.1.12 on 2026-08-08 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_companyuser_unique_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhotel',
            name='user',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='userhotel', to=settings.AUTH_USER_MODEL),
        ),
    ]
