# Generated by Django 5.1.12 on 2026-08-12 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_alter_userhotel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhotel',
            name='user',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='userhotels', to=settings.AUTH_USER_MODEL),
        ),
    ]
