# Generated by Django 5.1.12 on 2026-08-24 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_alter_userhotel_user'),
        ('static', '0068_grid_row_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='client',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.client'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='hotel',
            field=models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel'),
        ),
    ]
