# Generated by Django 5.1.12 on 2026-09-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_userrole_client_userrole_hotel'),
        ('static', '0070_formfield_data_source_form'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='unique_person_email_when_present'),
        ),
    ]
