# Generated by Django 5.1.12 on 2026-09-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_companyperson'),
        ('static', '0070_formfield_data_source_form'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='companyperson',
        #     name='unique_company_user',
        # ),
        # migrations.AddConstraint(
        #     model_name='companyperson',
        #     constraint=models.UniqueConstraint(fields=('company', 'person'), name='unique_company_person'),
        # ),
    ]
