# Generated by Django 5.1.12 on 2026-09-03 15:40

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_remove_companyperson_unique_company_user_and_more'),
        ('static', '0070_formfield_data_source_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPerson',
            fields=[
                ('client_person_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateTimeField(default=core.utilities.date_utilities.today)),
                ('end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.client')),
                ('effective_status', models.ForeignKey(db_column='effective_status_id', default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('person', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.person')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'client persons (base_client_person)',
                'db_table': 'base_client_person',
                'ordering': [],
            },
        ),
        migrations.DeleteModel(
            name='CompanyPerson',
        ),
        migrations.AddConstraint(
            model_name='clientperson',
            constraint=models.UniqueConstraint(fields=('client', 'person'), name='unique_client_person'),
        ),
    ]
