# Generated by Django 5.1.12 on 2026-09-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_clientperson_delete_companyperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_key',
            field=models.CharField(default='', max_length=40),
        ),
    ]
