# Generated by Django 5.1.5 on 2025-02-24 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('grouping', models.CharField(blank=True, max_length=30)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=40)),
                ('status_key', models.CharField(default='', max_length=50)),
                ('flag1', models.CharField(blank=True, default='', max_length=30)),
                ('group1', models.CharField(blank=True, default='', max_length=1)),
                ('order_by', models.CharField(blank=True, default='99', max_length=2)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'status (static_status)',
                'db_table': 'static_status',
                'ordering': [],
            },
        ),
    ]
