# Generated by Django 5.1.5 on 2025-03-07 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0002_alter_status_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('grouping', models.CharField(blank=True, max_length=60)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=60)),
                ('description_short', models.CharField(blank=True, max_length=30)),
                ('description_long', models.TextField(blank=True, default='')),
                ('description2', models.CharField(blank=True, max_length=30)),
                ('type_key', models.CharField(default='', max_length=60)),
                ('group1', models.CharField(blank=True, max_length=10)),
                ('flag1', models.CharField(default='', max_length=10)),
                ('flag2', models.CharField(default='', max_length=10)),
                ('attributes', models.TextField(blank=True, default='')),
                ('order_by', models.CharField(blank=True, default='99', max_length=2)),
                ('external_id', models.CharField(blank=True, max_length=60)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('parent_type', models.ForeignKey(db_column='parent_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'types (static_type)',
                'db_table': 'static_type',
                'ordering': [],
            },
        ),
    ]
