# Generated by Django 5.1.5 on 2025-03-10 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0003_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('grouping', models.CharField(blank=True, max_length=40)),
                ('client_key', models.CharField(max_length=70)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('parent_client', models.ForeignKey(db_column='parent_client_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.client')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='004', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'clients (static_client)',
                'db_table': 'static_client',
                'ordering': [],
            },
        ),
    ]
