# Generated by Django 5.1.5 on 2025-03-10 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0004_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='parent_client',
            field=models.ForeignKey(db_column='parent_client_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.client'),
        ),
    ]
