# Generated by Django 5.1.5 on 2025-03-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0006_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='currency',
            name='description',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='currency',
            name='order_by',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='', max_length=3),
        ),
    ]
