# Generated by Django 5.1.5 on 2025-04-11 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0007_currency_code_currency_description_currency_order_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(default='', max_length=50)),
                ('vms_identifier', models.CharField(max_length=4)),
                ('grouping', models.CharField(blank=True, max_length=40)),
                ('hotel_key', models.CharField(blank=True, max_length=50)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.client')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'hotels/cruise ships (static_hotel)',
                'db_table': 'static_hotel',
                'ordering': [],
            },
        ),
    ]
