# Generated by Django 5.1.5 on 2025-04-18 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_posmenu'),
        ('static', '0008_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosMenuItem',
            fields=[
                ('pos_menu_item_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.item')),
                ('pos_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.posmenu')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='00L', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'pos_menu/item junction (static_pos_menu_item)',
                'db_table': 'static_pos_menu_item',
                'ordering': [],
            },
        ),
    ]
