# Generated by Django 5.1.5 on 2025-04-18 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0009_posmenuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PosMenuItem',
        ),
    ]
