# Generated by Django 5.1.5 on 2025-06-24 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0010_delete_posmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('order_by', models.CharField(default='00', max_length=20)),
                ('description', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=30)),
                ('sub_title', models.CharField(max_length=80)),
                ('breadcrumb_name', models.CharField(max_length=20)),
                ('route', models.CharField(max_length=50)),
                ('params', models.TextField(default='')),
                ('icon', models.CharField(max_length=40)),
                ('grouping', models.CharField(blank=True, max_length=60)),
                ('menu_key', models.CharField(default='', max_length=60)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('parent_menu', models.ForeignKey(db_column='parent_menu_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.menu')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'menus (static_menu)',
                'db_table': 'static_menu',
                'ordering': [],
            },
        ),
    ]
