# Generated by Django 5.1.5 on 2025-06-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0011_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(default='', max_length=10)),
                ('description', models.CharField(default='', max_length=50)),
                ('grouping', models.CharField(blank=True, default='', max_length=40)),
                ('page_key', models.CharField(blank=True, default='', max_length=50)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'pages (static_page)',
                'db_table': 'static_page',
                'ordering': [],
            },
        ),
    ]
