# Generated by Django 5.1.5 on 2025-07-02 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0013_menu_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=60)),
                ('header', models.CharField(blank=True, default='', max_length=60)),
                ('data_source_application', models.CharField(default='', max_length=40)),
                ('data_source_model_name', models.CharField(default='', max_length=40)),
                ('save_button_label', models.CharField(default='', max_length=60)),
                ('save_button_action', models.CharField(default='saveAndClose', max_length=60)),
                ('grouping', models.CharField(blank=True, default='', max_length=40)),
                ('form_key', models.CharField(default='', max_length=60)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'forms (static_form)',
                'db_table': 'static_form',
                'ordering': [],
            },
        ),
    ]
