# Generated by Django 5.1.5 on 2025-07-05 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0014_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormControl',
            fields=[
                ('form_control_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('order_by', models.CharField(blank=True, max_length=2)),
                ('tab_name', models.CharField(default='', max_length=40)),
                ('label', models.CharField(default='', max_length=90)),
                ('name', models.CharField(default='', max_length=60)),
                ('default_value', models.CharField(default='', max_length=150)),
                ('data_source_application', models.CharField(default='', max_length=40)),
                ('data_source_model_name', models.CharField(default='', max_length=40)),
                ('data_source_filter', models.TextField(default='')),
                ('data_source_filter_effective_status', models.TextField(default='')),
                ('data_source_order', models.TextField(default='')),
                ('display_value', models.CharField(default='', max_length=60)),
                ('data_source_fields', models.CharField(default='', max_length=150)),
                ('data_source_fstring', models.CharField(default='', max_length=90)),
                ('data_source_key_field', models.CharField(default='', max_length=20)),
                ('disabled_create', models.BooleanField(default=False)),
                ('disabled_update', models.BooleanField(default=False)),
                ('required_flag', models.CharField(default='N', max_length=1)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.form')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'form controls (static_form_control)',
                'db_table': 'static_form_control',
                'ordering': [],
            },
        ),
    ]
