# Generated by Django 5.1.5 on 2025-07-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0016_formcontrol_control_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormControl',
            new_name='FormField',
        ),
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': [], 'verbose_name_plural': 'form fields (static_form_field)'},
        ),
        migrations.RenameField(
            model_name='formfield',
            old_name='form_control_id',
            new_name='form_field_id',
        ),
        migrations.AlterModelTable(
            name='formfield',
            table='static_form_field',
        ),
    ]
