# Generated by Django 5.1.5 on 2025-08-09 11:56

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0017_rename_formcontrol_formfield_alter_formfield_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('text_id', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('description_short', models.CharField(max_length=30)),
                ('description_long', models.TextField()),
                ('start_date', models.DateTimeField(default=core.utilities.date_utilities.beginning_of_time)),
                ('end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('grouping', models.CharField(blank=True, max_length=30)),
                ('text_key', models.CharField(default='', max_length=50)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('effective_status', models.ForeignKey(default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'freeform text including page content (static_text)',
                'db_table': 'static_text',
                'ordering': [],
            },
        ),
    ]
