# Generated by Django 5.1.12 on 2025-10-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0018_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_code',
            field=models.IntegerField(default=0),
        ),
    ]
