# Generated by Django 5.1.12 on 2025-11-22 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0020_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(default='', max_length=3, unique=True)),
                ('code', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=40)),
                ('route', models.CharField(default='', max_length=80)),
                ('view', models.CharField(default='', max_length=60)),
                ('module_path', models.CharField(default='', max_length=100)),
                ('grouping', models.CharField(default='', max_length=40)),
                ('process_key', models.CharField(default='', max_length=40)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'processes (static_process)',
                'db_table': 'static_process',
                'ordering': [],
            },
        ),
    ]
