# Generated by Django 5.1.12 on 2025-11-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0021_process'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
