# Generated by Django 5.1.12 on 2025-11-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0022_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='id',
        ),
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.CharField(default='', max_length=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
