# Generated by Django 5.1.12 on 2026-02-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0024_formextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formextra',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
