# Generated by Django 5.1.12 on 2026-02-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0025_alter_formextra_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormExtra',
        ),
    ]
