# Generated by Django 5.1.12 on 2026-02-10 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0026_delete_formextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormExtra',
            fields=[
                ('form_extra_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('order_by', models.CharField(default='00', max_length=2)),
                ('description', models.CharField(default='', max_length=50)),
                ('label', models.CharField(default='', max_length=50)),
                ('grouping', models.CharField(default='', max_length=30)),
                ('form_extra_key', models.CharField(default='', max_length=40)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.form')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'form extras (static_form_extra)',
                'db_table': 'static_form_extra',
                'ordering': [],
            },
        ),
    ]
