# Generated by Django 5.1.12 on 2026-02-10 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0027_formextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='formextra',
            name='target_form',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.form'),
        ),
    ]
