# Generated by Django 5.1.12 on 2026-02-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0028_formextra_target_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='mapping_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
