# Generated by Django 5.1.12 on 2026-02-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0029_formfield_mapping_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='custom_flag',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
