# Generated by Django 5.1.12 on 2026-02-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0030_formfield_custom_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='supports_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='supports_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='supports_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='supports_update',
            field=models.BooleanField(default=False),
        ),
    ]
