# Generated by Django 5.1.12 on 2026-02-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0031_process_supports_create_process_supports_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='public_key',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
