# Generated by Django 5.1.12 on 2026-02-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0032_hotel_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
