# Generated by Django 5.1.12 on 2026-03-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0033_alter_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='max_characters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formfield',
            name='min_characters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formfield',
            name='rows',
            field=models.IntegerField(default=0),
        ),
    ]
