# Generated by Django 5.1.12 on 2026-03-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0034_formfield_max_characters_formfield_min_characters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='max_characters',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='min_characters',
        ),
        migrations.AddField(
            model_name='formfield',
            name='max_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formfield',
            name='min_length',
            field=models.IntegerField(default=0),
        ),
    ]
