# Generated by Django 5.1.12 on 2026-03-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0035_remove_formfield_max_characters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='currency_key',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='currency',
            name='grouping',
            field=models.CharField(default='', max_length=30),
        ),
    ]
