# Generated by Django 5.1.12 on 2026-03-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0036_currency_currency_key_currency_grouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='hotel_required',
            field=models.BooleanField(default=True),
        ),
    ]
