# Generated by Django 5.1.12 on 2026-03-29 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0037_menu_hotel_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=False)),
                ('grouping', models.CharField(blank=True, default='', max_length=30)),
                ('table_key', models.CharField(default='', max_length=50)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('can_delete', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.form')),
                ('can_update', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.form')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'tables (static_table)',
                'db_table': 'static_table',
                'ordering': [],
            },
        ),
    ]
