# Generated by Django 5.1.12 on 2026-03-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0038_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='can_update',
            field=models.BooleanField(default=False),
        ),
    ]
