# Generated by Django 5.1.12 on 2026-03-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0040_grid_delete_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='title',
            field=models.CharField(default='', max_length=80),
        ),
    ]
