# Generated by Django 5.1.12 on 2026-03-30 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0041_grid_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridColumn',
            fields=[
                ('grid_column_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('order_by', models.CharField(blank=True, max_length=2)),
                ('description', models.CharField(blank=True, max_length=40)),
                ('description_short', models.CharField(blank=True, max_length=20)),
                ('column_definition', models.CharField(blank=True, max_length=40)),
                ('format', models.CharField(blank=True, default='', max_length=15)),
                ('style_class', models.CharField(default='', max_length=70)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('grid', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='static.grid')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'grid columns (static_grid_column)',
                'db_table': 'static_grid_column',
                'ordering': [],
            },
        ),
    ]
