# Generated by Django 5.1.12 on 2026-03-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0042_gridcolumn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gridcolumn',
            name='column_definition',
        ),
        migrations.AddField(
            model_name='gridcolumn',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
