# Generated by Django 5.1.12 on 2026-03-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0043_remove_gridcolumn_column_definition_gridcolumn_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gridcolumn',
            name='name',
        ),
        migrations.AddField(
            model_name='gridcolumn',
            name='field',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='gridcolumn',
            name='label',
            field=models.CharField(default='', max_length=25),
        ),
    ]
