# Generated by Django 5.1.12 on 2026-03-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0044_remove_gridcolumn_name_gridcolumn_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridcolumn',
            name='data_path',
            field=models.CharField(default='', max_length=60),
        ),
    ]
