# Generated by Django 5.1.12 on 2026-03-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0045_gridcolumn_data_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gridcolumn',
            name='data_path',
        ),
    ]
