# Generated by Django 5.1.12 on 2026-04-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0046_remove_gridcolumn_data_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='public_key',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
