# Generated by Django 5.1.12 on 2026-04-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0048_alter_hotel_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='generate_doc',
            field=models.BooleanField(default=False),
        ),
    ]
