# Generated by Django 5.1.12 on 2026-04-17 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0049_process_generate_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='grid',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.grid'),
        ),
    ]
