# Generated by Django 5.1.12 on 2026-04-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0050_menu_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='data_source_application',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='grid',
            name='data_source_model_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='grid',
            name='order_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
