# Generated by Django 5.1.12 on 2026-05-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0051_grid_data_source_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='group2',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
