# Generated by Django 5.1.12 on 2026-05-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0052_status_group2'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='css_class',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
