# Generated by Django 5.1.12 on 2026-05-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0053_status_css_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='form',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.form'),
        ),
    ]
