# Generated by Django 5.1.12 on 2026-05-18 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0054_grid_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='page',
            field=models.ForeignKey(default='000', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.page'),
        ),
    ]
