# Generated by Django 5.1.12 on 2026-05-19 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0055_grid_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='hotel_type',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type'),
        ),
    ]
