# Generated by Django 5.1.12 on 2026-05-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0056_menu_hotel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='external_code_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='type',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
