# Generated by Django 5.1.12 on 2026-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0057_type_external_code_type_alter_type_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='data_source_key',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
