# Generated by Django 5.1.12 on 2026-06-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0058_formfield_data_source_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='display_as',
            field=models.CharField(default='', max_length=80),
        ),
    ]
