# Generated by Django 5.1.12 on 2026-06-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0059_grid_display_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='selectable',
            field=models.BooleanField(default=False),
        ),
    ]
