# Generated by Django 5.1.12 on 2026-06-29 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0060_grid_selectable'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='form',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.form'),
        ),
    ]
