# Generated by Django 5.1.12 on 2026-07-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0061_process_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='user_required_flag',
            field=models.CharField(default='#', max_length=1),
        ),
    ]
