# Generated by Django 5.1.12 on 2026-07-03 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0062_process_user_required_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='grid',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.grid'),
        ),
    ]
