# Generated by Django 5.1.12 on 2026-07-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0063_process_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_key',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
