# Generated by Django 5.1.12 on 2026-08-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0064_alter_currency_currency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='display_pk',
            field=models.BooleanField(default=True),
        ),
    ]
