# Generated by Django 5.1.12 on 2026-08-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0065_grid_display_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridcolumn',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
