# Generated by Django 5.1.12 on 2026-08-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0066_gridcolumn_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='create_button_label',
            field=models.CharField(default='Add', max_length=30),
        ),
    ]
