# Generated by Django 5.1.12 on 2026-08-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0067_grid_create_button_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='row_action',
            field=models.CharField(default='update', max_length=10),
        ),
    ]
