# Generated by Django 5.1.12 on 2026-09-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0068_grid_row_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='data_source_allow_create_flag',
            field=models.CharField(default='#', max_length=1),
        ),
    ]
