# Generated by Django 5.1.12 on 2026-09-02 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0069_formfield_data_source_allow_create_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='data_source_form',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.form'),
        ),
    ]
