# Generated by Django 5.1.5 on 2025-03-15 22:16

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_alter_category_hotel'),
        ('static', '0005_alter_client_parent_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('order_by', models.CharField(default='99', max_length=2)),
                ('code', models.CharField(default='', max_length=15)),
                ('description', models.CharField(default='', max_length=50)),
                ('start_date', models.DateTimeField(default=core.utilities.date_utilities.beginning_of_time)),
                ('end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('grouping', models.CharField(default='', max_length=30)),
                ('room_key', models.CharField(default='', max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=50)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default='A9999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.category')),
                ('client', models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.client')),
                ('effective_status', models.ForeignKey(default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.hotel')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'rooms (res_room)',
                'db_table': 'res_room',
                'ordering': [],
            },
        ),
    ]
