# Generated by Django 5.1.5 on 2025-03-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0004_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='external_id',
        ),
    ]
