# Generated by Django 5.1.5 on 2025-03-22 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_company'),
        ('res', '0006_reservation'),
        ('static', '0005_alter_client_parent_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.person')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.reservation')),
                ('responsible_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.guest')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'guests (res_guest)',
                'db_table': 'res_guest',
                'ordering': [],
            },
        ),
    ]
