# Generated by Django 5.1.5 on 2025-03-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0007_alter_reservation_reservation_id_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='responsible_guest',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.guest'),
        ),
    ]
