# Generated by Django 5.1.5 on 2025-03-24 11:44

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0008_alter_guest_responsible_guest'),
        ('static', '0005_alter_client_parent_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRoom',
            fields=[
                ('guest_room_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('arrival_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('departure_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.guest')),
                ('room', models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.room')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'guest rooms (res_guest_room)',
                'db_table': 'res_guest_room',
                'ordering': [],
            },
        ),
    ]
