# Generated by Django 5.1.5 on 2025-04-02 19:08

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0009_guestroom'),
        ('static', '0007_currency_code_currency_description_currency_order_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosMenu',
            fields=[
                ('pos_menu_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateTimeField(default=core.utilities.date_utilities.today)),
                ('end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(default='00', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.currency')),
                ('effective_status', models.ForeignKey(default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('hotel', models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.hotel')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'Pont of Sale Menus (res_pos_menu)',
                'db_table': 'res_pos_menu',
                'ordering': [],
            },
        ),
    ]
