# Generated by Django 5.1.5 on 2025-04-02 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0010_posmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='posmenu',
            name='category',
            field=models.ForeignKey(default='A9999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.category'),
        ),
    ]
