# Generated by Django 5.1.5 on 2025-04-10 13:36

import core.utilities.date_utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0011_posmenu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posmenu',
            name='menu_end_date',
            field=models.DateTimeField(default=core.utilities.date_utilities.end_of_time),
        ),
        migrations.AddField(
            model_name='posmenu',
            name='menu_start_date',
            field=models.DateTimeField(default=core.utilities.date_utilities.today),
        ),
        migrations.AlterField(
            model_name='posmenu',
            name='start_date',
            field=models.DateTimeField(default=core.utilities.date_utilities.beginning_of_time),
        ),
    ]
