# Generated by Django 5.1.5 on 2025-04-11 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0012_posmenu_menu_end_date_posmenu_menu_start_date_and_more'),
        ('static', '0008_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='hotel',
            field=models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel'),
        ),
        migrations.AlterField(
            model_name='posmenu',
            name='hotel',
            field=models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel'),
        ),
    ]
