# Generated by Django 5.1.5 on 2025-04-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0013_alter_category_hotel_alter_posmenu_hotel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
