# Generated by Django 5.1.5 on 2025-04-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0014_delete_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_key',
            field=models.CharField(default='', max_length=50),
        ),
    ]
