# Generated by Django 5.1.5 on 2025-04-13 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_category'),
        ('res', '0015_alter_category_category_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posmenu',
            name='category',
            field=models.ForeignKey(default='A9999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.category'),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(default='A9999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.category'),
        ),
    ]
