# Generated by Django 5.1.5 on 2025-04-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0017_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PosMenu',
        ),
    ]
