# Generated by Django 5.1.5 on 2025-04-24 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0018_delete_posmenu'),
        ('static', '0010_delete_posmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.guest')),
                ('server_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.guest')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'transactions: sales and payments (res_transaction)',
                'db_table': 'res_transaction',
                'ordering': [],
            },
        ),
    ]
