# Generated by Django 5.1.5 on 2025-04-24 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0019_transaction'),
        ('static', '0010_delete_posmenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hotel',
            field=models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel'),
        ),
    ]
