# Generated by Django 5.1.5 on 2025-04-25 18:54

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0020_transaction_hotel'),
        ('static', '0010_delete_posmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=15)),
                ('description', models.CharField(blank=True, max_length=60)),
                ('event_start_date', models.DateTimeField(default=core.utilities.date_utilities.beginning_of_time)),
                ('event_end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('start_date', models.DateTimeField(default=core.utilities.date_utilities.today)),
                ('end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.client')),
                ('effective_status', models.ForeignKey(db_column='effective_status_id', default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('hotel', models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel')),
                ('parent_event', models.ForeignKey(db_column='parent_event_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.event')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'events (res_event)',
                'db_table': 'res_event',
                'ordering': [],
            },
        ),
    ]
