# Generated by Django 5.1.5 on 2025-04-27 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_externalmapping_external_pk_hoteltype'),
        ('res', '0022_transaction_event_transactionsale'),
        ('static', '0010_delete_posmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('transaction_sale_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=60)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('discount_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('discount_flat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.item')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.transaction')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'Transaction Items (res_transaction_item)',
                'db_table': 'res_transaction_item',
                'ordering': [],
            },
        ),
        migrations.DeleteModel(
            name='TransactionSale',
        ),
    ]
