# Generated by Django 5.1.5 on 2025-04-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0023_transactionitem_delete_transactionsale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionitem',
            old_name='transaction_sale_id',
            new_name='transaction_item_id',
        ),
    ]
