# Generated by Django 5.1.5 on 2025-04-27 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0024_rename_transaction_sale_id_transactionitem_transaction_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionItems', to='res.transaction'),
        ),
    ]
