# Generated by Django 5.1.5 on 2025-04-29 13:01

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_delete_hotelitem'),
        ('res', '0025_alter_transactionitem_transaction'),
        ('static', '0010_delete_posmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelItem',
            fields=[
                ('hotel_item_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateTimeField(default=core.utilities.date_utilities.beginning_of_time)),
                ('end_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('effective_status', models.ForeignKey(default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('hotel', models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel')),
                ('item', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.item')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'hotel items (special items) (res_hotel_item)',
                'db_table': 'res_hotel_item',
                'ordering': [],
            },
        ),
    ]
