# Generated by Django 5.1.5 on 2025-04-29 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0026_hotelitem'),
        ('static', '0010_delete_posmenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelitem',
            name='special_item_type',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type'),
        ),
    ]
