# Generated by Django 5.1.5 on 2025-05-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0027_hotelitem_special_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_key',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='event',
            name='grouping',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='guest',
            name='grouping',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_key',
            field=models.CharField(default='', max_length=70),
        ),
    ]
