# Generated by Django 5.1.5 on 2025-05-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0028_event_event_key_event_grouping_guest_grouping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='grouping',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_key',
            field=models.CharField(default='', max_length=25),
        ),
    ]
