# Generated by Django 5.1.12 on 2025-10-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0029_reservation_grouping_reservation_reservation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='authorized_to_charge',
            field=models.BooleanField(default=False),
        ),
    ]
