# Generated by Django 5.1.12 on 2025-10-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0030_guest_authorized_to_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='authorized_to_charge',
        ),
        migrations.AddField(
            model_name='guest',
            name='authorized_to_charge_flag',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
