# Generated by Django 5.1.12 on 2025-12-13 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0032_transaction_user'),
        ('static', '0023_remove_process_id_alter_process_process_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(default='00', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.currency'),
        ),
    ]
