# Generated by Django 5.1.12 on 2025-12-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0033_transaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
