# Generated by Django 5.1.12 on 2025-12-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0034_transaction_external_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_authorization_code',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
