# Generated by Django 5.1.12 on 2026-01-23 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0035_transaction_external_authorization_code'),
        ('static', '0023_remove_process_id_alter_process_process_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelExtension',
            fields=[
                ('hotel_extension_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('current_event', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.event')),
                ('hotel', models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.hotel')),
            ],
            options={
                'verbose_name_plural': 'hotels/cruise ships extension (res_hotel_extension)',
                'db_table': 'res_hotel_extension',
                'ordering': [],
            },
        ),
    ]
