# Generated by Django 5.1.12 on 2026-01-23 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0036_hotelextension'),
        ('static', '0023_remove_process_id_alter_process_process_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelextension',
            name='status',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status'),
        ),
        migrations.AddField(
            model_name='hotelextension',
            name='type',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type'),
        ),
    ]
