# Generated by Django 5.1.12 on 2026-02-26 13:24

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0037_hotelextension_status_hotelextension_type'),
        ('static', '0032_hotel_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestActivity',
            fields=[
                ('guest_activity_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('arrival_date', models.DateTimeField(default=core.utilities.date_utilities.end_of_time)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.event')),
                ('guest', models.ForeignKey(default='A99999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.guest')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'guest activities (res_guest_activity)',
                'db_table': 'res_guest_activity',
                'ordering': [],
            },
        ),
    ]
