# Generated by Django 5.1.12 on 2026-02-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0038_guestactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='rfid_uid',
            field=models.CharField(default='', max_length=32),
        ),
    ]
