# Generated by Django 5.1.12 on 2026-03-01 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0039_guest_rfid_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestroom',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestRooms', to='res.guest'),
        ),
    ]
