# Generated by Django 5.1.12 on 2026-04-03 19:13

import core.utilities.date_utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0040_alter_guestroom_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestroom',
            name='arrival_date',
            field=models.DateField(default=core.utilities.date_utilities.end_of_time),
        ),
        migrations.AlterField(
            model_name='guestroom',
            name='departure_date',
            field=models.DateField(default=core.utilities.date_utilities.end_of_time),
        ),
    ]
