# Generated by Django 5.1.12 on 2026-04-07 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0041_alter_guestroom_arrival_date_and_more'),
        ('static', '0048_alter_hotel_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.ForeignKey(default='01N', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status'),
        ),
    ]
