# Generated by Django 5.1.12 on 2026-04-19 22:08

import core.utilities.date_utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0042_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateField(default=core.utilities.date_utilities.end_of_time),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.DateField(default=core.utilities.date_utilities.beginning_of_time),
        ),
    ]
