# Generated by Django 5.1.12 on 2026-04-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0043_alter_event_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_ext',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
