# Generated by Django 5.1.12 on 2026-04-28 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0044_event_description_ext'),
        ('static', '0051_grid_data_source_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelitem',
            name='status',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status'),
        ),
    ]
