# Generated by Django 5.1.12 on 2026-04-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0045_hotelitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description_ext',
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='description_extension',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
