# Generated by Django 5.1.12 on 2026-05-02 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0046_remove_event_description_ext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='res.transaction'),
        ),
    ]
