# Generated by Django 5.1.12 on 2026-05-06 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0047_alter_transactionitem_transaction'),
        ('static', '0051_grid_data_source_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelextension',
            name='hotel',
            field=models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='hotel_extensions', to='static.hotel'),
        ),
    ]
