# Generated by Django 5.1.12 on 2026-06-23 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0049_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='accessible_flag',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.floor'),
        ),
        migrations.AddField(
            model_name='room',
            name='lower_berths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='maximum_occupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='upper_berths',
            field=models.IntegerField(default=0),
        ),
    ]
