# Generated by Django 5.1.12 on 2026-07-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0050_room_accessible_flag_room_floor_room_lower_berths_and_more'),
        ('static', '0063_process_grid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRoom',
            fields=[
                ('event_room_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('notes', models.TextField(default='')),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.event')),
                ('inventory_status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('room', models.ForeignKey(default='A000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.room')),
                ('status', models.ForeignKey(default='019', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'Event room inventory (res_event_room)',
                'db_table': 'res_event_room',
                'ordering': [],
                'constraints': [models.UniqueConstraint(fields=('event', 'room'), name='unique_event_room')],
            },
        ),
    ]
