# Generated by Django 5.1.12 on 2026-07-06 22:51

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0051_eventroom'),
        ('static', '0063_process_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventroom',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='eventroom',
            name='status',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status'),
        ),
        migrations.CreateModel(
            name='EventRoomAssignment',
            fields=[
                ('event_room_assignment_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('assignment_start_date', models.DateField(default=core.utilities.date_utilities.today)),
                ('assignment_end_date', models.DateField(default=core.utilities.date_utilities.today)),
                ('notes', models.TextField(blank=True, default='')),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('event_room', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.eventroom')),
                ('reservation', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.reservation')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'event room assignments (res_event_room_assignment)',
                'db_table': 'res_event_room_assignment',
                'ordering': [],
            },
        ),
    ]
