# Generated by Django 5.1.12 on 2026-07-06 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_location_grouping_location_location_key_and_more'),
        ('res', '0052_alter_eventroom_notes_alter_eventroom_status_and_more'),
        ('static', '0063_process_grid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategoryPrice',
            fields=[
                ('event_category_price_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default='A0000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.category')),
                ('currency', models.ForeignKey(default='00', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.currency')),
                ('event', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.event')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'event category prices (res_event_category_price)',
                'db_table': 'res_event_category_price',
                'ordering': [],
            },
        ),
    ]
