# Generated by Django 5.1.12 on 2026-07-08 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0053_eventcategoryprice'),
        ('static', '0063_process_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelextension',
            name='currency',
            field=models.ForeignKey(default='99', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.currency'),
        ),
    ]
