# Generated by Django 5.1.12 on 2026-07-16 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0054_hotelextension_currency'),
        ('static', '0063_process_grid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientExtension',
            fields=[
                ('client_extension_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='hotel_extensions', to='static.hotel')),
                ('currency', models.ForeignKey(default='99', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.currency')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'client extension (res_client_extension)',
                'db_table': 'res_client_extension',
                'ordering': [],
            },
        ),
    ]
