# Generated by Django 5.1.12 on 2026-07-19 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0056_alter_clientextension_client'),
        ('static', '0063_process_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientextension',
            name='client',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='client_extensions', to='static.client'),
        ),
    ]
