# Generated by Django 5.1.12 on 2026-07-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0058_eventcurrency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcurrency',
            options={'ordering': [], 'verbose_name_plural': 'event/currencies (res_event_currency)'},
        ),
        migrations.AlterModelTable(
            name='eventcurrency',
            table='res_event_currency',
        ),
    ]
