# Generated by Django 5.1.12 on 2026-07-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0059_alter_eventcurrency_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcurrency',
            options={'ordering': [], 'verbose_name_plural': 'event/currencies (res_event__currency)'},
        ),
        migrations.AlterModelTable(
            name='eventcurrency',
            table='res_event__currency',
        ),
    ]
