# Generated by Django 5.1.12 on 2026-07-31 12:53

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0062_alter_eventcurrency_options_and_more'),
        ('static', '0064_alter_currency_currency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategoryprice',
            name='effective_status',
            field=models.ForeignKey(default='021', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status'),
        ),
        migrations.AddField(
            model_name='eventcategoryprice',
            name='end_date',
            field=models.DateTimeField(default=core.utilities.date_utilities.end_of_time),
        ),
        migrations.AddField(
            model_name='eventcategoryprice',
            name='price_type',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type'),
        ),
        migrations.AddField(
            model_name='eventcategoryprice',
            name='start_date',
            field=models.DateTimeField(default=core.utilities.date_utilities.beginning_of_time),
        ),
    ]
