# Generated by Django 5.1.12 on 2026-07-31 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0063_eventcategoryprice_effective_status_and_more'),
        ('static', '0064_alter_currency_currency_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategoryprice',
            name='price_type',
        ),
        migrations.AddField(
            model_name='eventcategoryprice',
            name='occupancy_type',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type'),
        ),
        migrations.AddField(
            model_name='eventcategoryprice',
            name='rate_type',
            field=models.ForeignKey(default='03B', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type'),
        ),
    ]
