# Generated by Django 5.1.12 on 2026-08-28 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0064_remove_eventcategoryprice_price_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(default='A99999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.event'),
        ),
    ]
