# Generated by Django 5.1.12 on 2026-08-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0065_reservation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='adult_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='child_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='infant_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
