# Generated by Django 5.1.12 on 2026-08-31 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0066_reservation_adult_count_reservation_child_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='res.reservation'),
        ),
    ]
