# Generated by Django 5.1.12 on 2026-08-31 16:16

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0067_alter_guest_reservation'),
        ('static', '0068_grid_row_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='booking_birth_date',
            field=models.DateField(default=core.utilities.date_utilities.beginning_of_time),
        ),
        migrations.AddField(
            model_name='guest',
            name='booking_first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='guest',
            name='booking_gender_type',
            field=models.ForeignKey(default='700', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type'),
        ),
        migrations.AddField(
            model_name='guest',
            name='booking_last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='guest',
            name='booking_middle_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
