# Generated by Django 5.1.12 on 2026-09-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_userrole_client_userrole_hotel'),
        ('res', '0068_guest_booking_birth_date_guest_booking_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='contact_person',
            field=models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.person'),
        ),
    ]
