# Generated by Django 5.1.12 on 2026-09-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0069_reservation_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
