# Generated by Django 5.1.12 on 2026-09-05 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_alter_category_category_key'),
        ('res', '0070_reservation_room_count'),
        ('static', '0070_formfield_data_source_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('reservation_room_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('occupancy', models.PositiveSmallIntegerField(default=0)),
                ('order_by', models.CharField(blank=True, default='99', max_length=2)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default='A0001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.category')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_roms', to='res.reservation')),
                ('room', models.ForeignKey(default='A999', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.room')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'reservation rooms (res_reservation_room)',
                'db_table': 'res_reservation_room',
                'ordering': [],
            },
        ),
    ]
