# Generated by Django 5.1.12 on 2026-09-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0071_reservationroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='adult_count',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='child_count',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='infant_count',
        ),
        migrations.AddField(
            model_name='reservationroom',
            name='adult_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservationroom',
            name='child_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservationroom',
            name='infant_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
