# Generated by Django 5.1.12 on 2026-09-14 10:41

import core.utilities.date_utilities
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_alter_category_category_key'),
        ('res', '0072_remove_reservation_adult_count_and_more'),
        ('static', '0070_formfield_data_source_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRoomGuest',
            fields=[
                ('reservation_room_guest_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('booking_first_name', models.CharField(default='', max_length=20)),
                ('booking_last_name', models.CharField(default='', max_length=20)),
                ('booking_middle_name', models.CharField(blank=True, default='', max_length=40)),
                ('booking_birth_date', models.DateField(default=core.utilities.date_utilities.beginning_of_time)),
                ('grouping', models.CharField(blank=True, default='', max_length=40)),
                ('reservation_room_guest_key', models.CharField(default='', max_length=70)),
                ('authorized_to_charge_flag', models.CharField(default='N', max_length=1)),
                ('rfid_uid', models.CharField(default='', max_length=32)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('booking_gender_type', models.ForeignKey(default='700', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
                ('person', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.person')),
                ('reservation_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_room_guests', to='res.reservationroom')),
                ('responsible_reservation_room_guest', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='res.reservationroomguest')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'reservation room guests (res_reservation_room_guest)',
                'db_table': 'res_reservation_room_guest',
                'ordering': [],
            },
        ),
    ]
