# Generated by Django 5.1.12 on 2026-09-16 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0073_reservationroomguest'),
        ('static', '0070_formfield_data_source_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationroomguest',
            name='occupancy_type',
            field=models.ForeignKey(default='03Q', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type'),
        ),
        migrations.AlterField(
            model_name='reservationroomguest',
            name='type',
            field=models.ForeignKey(default='03T', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type'),
        ),
    ]
