# Generated by Django 5.1.12 on 2026-09-30 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0074_reservationroomguest_occupancy_type_and_more'),
        ('static', '0070_formfield_data_source_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationroom',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_rooms', to='res.reservation'),
        ),
        migrations.CreateModel(
            name='ReservationPrice',
            fields=[
                ('reservation_price_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('static_flag', models.CharField(blank=True, default='N', max_length=1)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(default='00', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.currency')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_prices', to='res.reservation')),
                ('reservation_room', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.reservationroom')),
                ('reservation_room_guest', models.ForeignKey(default='A00000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='res.reservationroomguest')),
                ('status', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.status')),
                ('type', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='static.type')),
            ],
            options={
                'verbose_name_plural': 'reservation prices (res_reservation_price)',
                'db_table': 'res_reservation_price',
                'ordering': [],
            },
        ),
    ]
