# Generated by Django 5.1.12 on 2026-10-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0075_alter_reservationroom_reservation_reservationprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationroomguest',
            name='guest_number',
            field=models.CharField(default='00', max_length=2),
        ),
    ]
